from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ── Enumerations ──────────────────────────────────────────────────────────────

class IncidentType(str, Enum):
    THROUGHPUT_DROP = "throughput_drop"
    QUALITY_ISSUE = "quality_issue"
    SUPPLIER_DELAY = "supplier_delay"
    EQUIPMENT_DOWNTIME = "equipment_downtime"
    SAFETY_CONCERN = "safety_concern"
    UNKNOWN = "unknown"


class Severity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


# ── Input ─────────────────────────────────────────────────────────────────────

class Incident(BaseModel):
    """Raw incident submitted by the operations manager."""
    id: str = Field(description="Unique incident identifier, e.g. INC-2024-042")
    description: str = Field(description="Free-text description from the operator")
    plant_id: str = Field(description="Plant identifier, e.g. PLANT-A")
    line_id: Optional[str] = Field(default=None, description="Production line, e.g. LINE-B")
    incident_type: Optional[IncidentType] = None
    severity: Optional[Severity] = None
    timestamp: Optional[str] = None
    raw_metrics: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional dict of live sensor/KPI values at time of incident",
    )


# ── Intermediate ──────────────────────────────────────────────────────────────

class AgentFinding(BaseModel):
    """Output produced by a single domain agent."""
    agent_name: str
    domain: str
    analysis_summary: str
    anomalies_detected: List[str] = Field(default_factory=list)
    relevant_doc_titles: List[str] = Field(default_factory=list)
    contributing_factors: List[str] = Field(default_factory=list)
    raw_tool_outputs: List[str] = Field(default_factory=list)


# ── Root-cause hypothesis ─────────────────────────────────────────────────────

class RootCauseHypothesis(BaseModel):
    """A single ranked hypothesis with confidence score."""
    rank: int = Field(description="1 = most likely")
    hypothesis: str
    confidence: float = Field(ge=0.0, le=1.0, description="0.0–1.0")
    confidence_label: str = Field(description="HIGH / MEDIUM / LOW")
    supporting_evidence: List[str] = Field(default_factory=list)
    contributing_agents: List[str] = Field(default_factory=list)
    recommended_actions: List[str] = Field(default_factory=list)
    estimated_resolution_time: Optional[str] = None


# ── Final report ──────────────────────────────────────────────────────────────

class IncidentReport(BaseModel):
    """Full root-cause analysis report delivered to the operations manager."""
    incident: Incident
    agents_invoked: List[str] = Field(default_factory=list)
    findings: List[AgentFinding] = Field(default_factory=list)
    root_cause_hypotheses: List[RootCauseHypothesis] = Field(default_factory=list)
    executive_summary: str = ""
    recommended_immediate_actions: List[str] = Field(default_factory=list)
    recommended_preventive_actions: List[str] = Field(default_factory=list)
    estimated_production_impact: str = ""
    confidence_note: str = ""


# ── Post-RCA action documents ─────────────────────────────────────────────────

class ShiftHandoffNote(BaseModel):
    """Structured shift handoff note drafted by the ShiftHandoffAgent."""
    incident_id: str
    outgoing_shift: str = ""
    incoming_shift: str = ""
    situation_summary: str = Field(description="What happened and current status")
    actions_completed: List[str] = Field(default_factory=list)
    pending_actions: List[str] = Field(default_factory=list, description="Actions not yet completed")
    watch_items: List[str] = Field(default_factory=list, description="Things the next shift must monitor")
    do_not_restart_until: List[str] = Field(
        default_factory=list,
        description="Conditions that must be met before restarting production",
    )
    escalation_contacts: List[str] = Field(default_factory=list)
    raw_note: str = ""


class MaintenanceRequestItem(BaseModel):
    """A single line item in a maintenance work order."""
    item_number: int
    equipment_id: str
    problem_description: str
    work_requested: str
    parts_required: List[str] = Field(default_factory=list)
    estimated_duration_hours: Optional[float] = None
    safety_precautions: List[str] = Field(default_factory=list)


class MaintenanceRequest(BaseModel):
    """Formal maintenance work order generated by the MaintenanceRequestAgent."""
    wo_number: str
    incident_id: str
    priority: str = Field(description="CRITICAL / HIGH / MEDIUM / LOW")
    requested_by: str = ""
    requested_date: Optional[str] = None
    required_completion_date: Optional[str] = None
    line_id: str = ""
    plant_id: str = ""
    work_items: List[MaintenanceRequestItem] = Field(default_factory=list)
    special_instructions: str = ""
    approvals_required: List[str] = Field(default_factory=list)
    raw_request: str = ""


class CorrectiveActionItem(BaseModel):
    """A single corrective action in a CAP."""
    action_number: int
    category: str = Field(description="IMMEDIATE / SHORT_TERM / LONG_TERM / PREVENTIVE")
    action: str
    owner: str
    due_date: str
    success_criteria: str
    status: str = "OPEN"


class CorrectiveActionPlan(BaseModel):
    """Structured CAP (Corrective Action Plan) generated by the CorrectiveActionAgent."""
    cap_id: str
    incident_id: str
    root_cause_addressed: str
    problem_statement: str = ""
    actions: List[CorrectiveActionItem] = Field(default_factory=list)
    effectiveness_kpis: List[str] = Field(default_factory=list)
    review_date: str = ""
    approver: str = ""
    raw_plan: str = ""


class SupplierQuestion(BaseModel):
    """A single question for a supplier inquiry."""
    question_number: int
    category: str = Field(description="E.g. ROOT_CAUSE / TIMELINE / PREVENTION / COMPENSATION")
    question: str
    context: str = ""
    expected_response_format: str = ""


class SupplierQuestionnaire(BaseModel):
    """Structured supplier questions generated by the SupplierQuestionsAgent."""
    supplier_name: str
    incident_id: str
    po_references: List[str] = Field(default_factory=list)
    urgency: str = Field(description="IMMEDIATE (< 24h) / STANDARD (3-5 days)")
    questions: List[SupplierQuestion] = Field(default_factory=list)
    requested_deliverables: List[str] = Field(
        default_factory=list,
        description="Documents/data requested from supplier alongside answers",
    )
    escalation_note: str = ""
    raw_questionnaire: str = ""


# ── LangGraph state ───────────────────────────────────────────────────────────

class ManufacturingState(BaseModel):
    """Shared mutable state threaded through the LangGraph graph."""
    incident: Incident
    agents_to_run: List[str] = Field(default_factory=list)
    findings: List[AgentFinding] = Field(default_factory=list)
    report: Optional[IncidentReport] = None
    shift_handoff: Optional[ShiftHandoffNote] = None
    maintenance_request: Optional[MaintenanceRequest] = None
    corrective_action_plan: Optional[CorrectiveActionPlan] = None
    supplier_questionnaire: Optional[SupplierQuestionnaire] = None
    error: Optional[str] = None
